name: Python CI for main and develop branches

on:
  push:
    branches:
      - main
      - develop  # This ensures the workflow triggers for both `main` and `develop`
      - 'release/*'
      
  pull_request:
    branches:
      - main
      - develop  # This ensures PRs to both branches are checked
      - 'release/*'
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # This step checks out your repository code so that other steps can use it

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specifies the Python version to use in the workflow

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to the latest version
          pip install -r requirements.txt     # Installs the dependencies in requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q  # Runs the tests using pytest
